# The listing model: one surplus item a member posts so others can request it.
# The shape matches the ERD in technical-design.md section 4 exactly.
#
# A few columns use Postgres-only types on purpose:
#   - dietary_tags and allergen_tags are arrays of text (TEXT[]).
#   - pickup_window is a single range column holding the start and end as one
#     timezone-aware range value (TSTZRANGE).
#   - status is a real Postgres enum type (listing_status).
# Because of these types, the whole model lives on Postgres; there is no
# SQLite fallback for it.

import uuid
from datetime import datetime
from typing import List, Optional

from sqlalchemy import (
    CheckConstraint,
    Enum as SAEnum,
    ForeignKey,
    Index,
    Integer,
    Text,
    TIMESTAMP,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, Range, TSTZRANGE, UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


class Listing(Base):
    __tablename__ = "listing"

    # The primary key gets two defaults on purpose. The Python default lets the
    # route read new_listing.id right after a flush without a database round
    # trip. The server default has to live on the model too, because the
    # migration is autogenerated: Alembic does not invent a server default from
    # a Python one, so without this line the generated column would lack it. It
    # also backstops any insert that bypasses the ORM (seed via raw SQL).
    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
    )
    # The member who created the listing. This is the owner.
    owner_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("member.id"),
    )
    title: Mapped[str] = mapped_column(Text)
    # The column allows null so later stories are not forced to carry a
    # description, but the US-15 create path requires a non-blank value.
    description: Mapped[Optional[str]] = mapped_column(Text)
    category: Mapped[Optional[str]] = mapped_column(Text)
    # Free-form tags, stored exactly as typed. The empty array is the default,
    # so a listing with no tags is a normal row.
    dietary_tags: Mapped[List[str]] = mapped_column(ARRAY(Text), server_default=text("'{}'"))
    allergen_tags: Mapped[List[str]] = mapped_column(ARRAY(Text), server_default=text("'{}'"))
    total_quantity: Mapped[int] = mapped_column(Integer)
    # Starts equal to total_quantity at create time. The request flow in later
    # stories lowers it as the item is claimed.
    remaining_quantity: Mapped[int] = mapped_column(Integer)
    # The pickup window is one range value: lower bound is the start, upper
    # bound is the end, lower-inclusive and upper-exclusive.
    pickup_window: Mapped[Range[datetime]] = mapped_column(TSTZRANGE)
    status: Mapped[str] = mapped_column(
        SAEnum("active", "claimed", "expired", "cancelled", "deactivated", name="listing_status"),
        server_default="active",
    )
    # Null until an admin deactivates the listing (US-27). It records who did
    # it. US-15 always leaves this null.
    deactivated_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("member.id"),
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        server_default=text("now()"),
    )

    # The constraints and the two GIN indexes live on the model so the
    # autogenerated migration picks them up with no hand-editing. The check
    # constraints guard the quantity invariants; the GIN indexes make the tag
    # arrays searchable for US-06's tag filtering.
    __table_args__ = (
        CheckConstraint("total_quantity > 0", name="ck_listing_total_quantity_positive"),
        CheckConstraint("remaining_quantity >= 0", name="ck_listing_remaining_quantity_nonneg"),
        CheckConstraint("remaining_quantity <= total_quantity", name="ck_listing_remaining_le_total"),
        Index("ix_listing_dietary_tags", "dietary_tags", postgresql_using="gin"),
        Index("ix_listing_allergen_tags", "allergen_tags", postgresql_using="gin"),
    )

    # listing has two foreign keys to member (owner_id and deactivated_by), so
    # a plain relationship would be ambiguous. Naming the foreign key column
    # tells SQLAlchemy which one the owner relationship follows, the same way
    # InviteToken names its creator and redeemer foreign keys.
    owner: Mapped["Member"] = relationship(foreign_keys="[Listing.owner_id]")  # noqa: F821
