"""create listing

Revision ID: 02be483a62ce
Revises: e4f5a6b7c804
Create Date: 2026-06-18 23:04:25.509264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "02be483a62ce"
down_revision: Union[str, Sequence[str], None] = "e4f5a6b7c804"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "active",
        "claimed",
        "expired",
        "cancelled",
        "deactivated",
        name="listing_status",
    ).create(op.get_bind())
    op.create_table(
        "listing",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column(
            "dietary_tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "allergen_tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("total_quantity", sa.Integer(), nullable=False),
        sa.Column("remaining_quantity", sa.Integer(), nullable=False),
        sa.Column("pickup_window", postgresql.TSTZRANGE(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "active",
                "claimed",
                "expired",
                "cancelled",
                "deactivated",
                name="listing_status",
                create_type=False,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("deactivated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "remaining_quantity <= total_quantity", name="ck_listing_remaining_le_total"
        ),
        sa.CheckConstraint(
            "remaining_quantity >= 0", name="ck_listing_remaining_quantity_nonneg"
        ),
        sa.CheckConstraint(
            "total_quantity > 0", name="ck_listing_total_quantity_positive"
        ),
        sa.ForeignKeyConstraint(
            ["deactivated_by"],
            ["member.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["member.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_listing_allergen_tags",
        "listing",
        ["allergen_tags"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_listing_dietary_tags",
        "listing",
        ["dietary_tags"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_listing_dietary_tags", table_name="listing", postgresql_using="gin"
    )
    op.drop_index(
        "ix_listing_allergen_tags", table_name="listing", postgresql_using="gin"
    )
    op.drop_table("listing")
    sa.Enum(
        "active",
        "claimed",
        "expired",
        "cancelled",
        "deactivated",
        name="listing_status",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
