"""backfill admin audit log

Revision ID: 125c82a0a1c1
Revises: 13d5ea1d2189
Create Date: 2026-07-29 17:29:30.666871

Reconstructs historical admin_audit_log rows from suspension_record and
listing.deactivated_by/deactivated_at, the two tables that already recorded
this history before admin_audit_log existed (US-35).

A data-only migration, not autogenerated (no schema changes here, so this
one never hits the known message/message_thread autogenerate bug - there is
nothing to remove by hand in this file).

This lives inside the migration, not a one-off script under app/, because
conftest.py builds every test database purely by running migrations to
head - a separate script would never run in that path (or in a plain
`npm run db:migrate` on a fresh environment) and so would silently produce
zero historical rows anywhere except a machine someone remembered to run it
on by hand.

Known, accepted gap: a listing that was deactivated by an admin and later
reactivated leaves no trace here. reactivate_listing_as_admin clears
deactivated_by/deactivated_at back to null on reactivation, so only
listings that are CURRENTLY deactivated can be backfilled - a past
deactivate-then-reactivate cycle produces zero rows for that cycle. There is
no historical record left anywhere in the schema to reconstruct it from.

Similarly, backfilled member_unsuspended rows always have a null admin_id:
suspension_record only ever recorded WHEN a suspension was lifted
(lifted_at), never WHO lifted it, so there is no actor to attribute for
those rows specifically. Every row written going forward (by
record_audit_log_entry, called from the routers directly) always has a real
admin_id.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "125c82a0a1c1"
down_revision: Union[str, Sequence[str], None] = "13d5ea1d2189"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


admin_audit_log = sa.table(
    "admin_audit_log",
    sa.column("admin_id", sa.UUID()),
    sa.column("action", sa.Text()),
    sa.column("target_type", sa.Text()),
    sa.column("target_id", sa.UUID()),
    sa.column("reason", sa.Text()),
    sa.column("created_at", sa.TIMESTAMP(timezone=True)),
)

suspension_record = sa.table(
    "suspension_record",
    sa.column("member_id", sa.UUID()),
    sa.column("admin_id", sa.UUID()),
    sa.column("reason", sa.Text()),
    sa.column("created_at", sa.TIMESTAMP(timezone=True)),
    sa.column("lifted_at", sa.TIMESTAMP(timezone=True)),
)

listing = sa.table(
    "listing",
    sa.column("id", sa.UUID()),
    sa.column("deactivated_by", sa.UUID()),
    sa.column("deactivated_at", sa.TIMESTAMP(timezone=True)),
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    rows_to_insert = []

    for record in bind.execute(sa.select(suspension_record)).mappings():
        rows_to_insert.append(
            {
                "admin_id": record["admin_id"],
                "action": "member_suspended",
                "target_type": "member",
                "target_id": record["member_id"],
                "reason": record["reason"],
                "created_at": record["created_at"],
            }
        )
        if record["lifted_at"] is not None:
            # No actor recorded in the source table for who lifted it - see
            # the module docstring.
            rows_to_insert.append(
                {
                    "admin_id": None,
                    "action": "member_unsuspended",
                    "target_type": "member",
                    "target_id": record["member_id"],
                    "reason": None,
                    "created_at": record["lifted_at"],
                }
            )

    deactivated_listings = bind.execute(
        sa.select(listing).where(listing.c.deactivated_by.is_not(None))
    ).mappings()
    for row in deactivated_listings:
        rows_to_insert.append(
            {
                "admin_id": row["deactivated_by"],
                "action": "listing_deactivated",
                "target_type": "listing",
                "target_id": row["id"],
                "reason": None,
                "created_at": row["deactivated_at"],
            }
        )

    if rows_to_insert:
        op.bulk_insert(admin_audit_log, rows_to_insert)


def downgrade() -> None:
    """Downgrade schema."""
    # Safe and symmetric as long as this runs immediately after its own
    # upgrade() in the same migration chain (this project's test DBs always
    # migrate from empty to head, never interleaved with live writes), which
    # is also why this can delete unconditionally rather than only the rows
    # it itself inserted.
    op.execute("DELETE FROM admin_audit_log")
