"""add listing deactivated_at

Revision ID: 69cd7509ed47
Revises: 877a55149d7f
Create Date: 2026-07-26 08:57:53.583012

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "69cd7509ed47"
down_revision: Union[str, Sequence[str], None] = "877a55149d7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listing",
        sa.Column("deactivated_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # Autogenerate also proposed dropping the live message and message_thread
    # tables, because their models are not registered in app.models.__init__.
    # Those drops were removed by hand, the same fix the review and
    # suspension_record migrations applied: the tables are real and in use.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("listing", "deactivated_at")
    # ### end Alembic commands ###
