"""create member report

Revision ID: 73ede1052e38
Revises: 69cd7509ed47
Create Date: 2026-07-29 17:07:28.186969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "73ede1052e38"
down_revision: Union[str, Sequence[str], None] = "69cd7509ed47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member_report",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("reporter_id", sa.UUID(), nullable=False),
        sa.Column("target_member_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Text(), server_default=sa.text("'open'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('open', 'resolved')", name="ck_member_report_status"
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"],
            ["member.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["member.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_member_id"],
            ["member.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_member_report_target_status",
        "member_report",
        ["target_member_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_member_report_one_open",
        "member_report",
        ["reporter_id", "target_member_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    # Autogenerate also proposed dropping the live message and message_thread
    # tables, since app/models/thread.py is not registered in
    # app/models/__init__.py. Removed by hand, the same fix the review and
    # suspension_record migrations applied.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_member_report_one_open",
        table_name="member_report",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index("ix_member_report_target_status", table_name="member_report")
    op.drop_table("member_report")
    # ### end Alembic commands ###
