"""create review

Revision ID: d703db53f978
Revises: 9760b7a69354
Create Date: 2026-07-19 17:14:27.528017

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d703db53f978"
down_revision: Union[str, Sequence[str], None] = "9760b7a69354"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("reviewee_id", sa.UUID(), nullable=False),
        sa.Column("reviewee_role", sa.Text(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("disabled_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("disabled_by", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "reviewee_role IN ('listing_owner', 'requestor')",
            name="ck_review_reviewee_role",
        ),
        sa.CheckConstraint(
            "rating >= 1 AND rating <= 5", name="ck_review_rating_range"
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claim.id"],
        ),
        sa.ForeignKeyConstraint(
            ["disabled_by"],
            ["member.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewee_id"],
            ["member.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["member.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("claim_id", "reviewer_id", name="uq_review_claim_reviewer"),
    )
    # Autogenerate also proposed dropping the live message and message_thread
    # tables, because their models are not registered in app.models.__init__.
    # Those drops were removed by hand: the tables are real and in use.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review")
    # ### end Alembic commands ###
